### ISSUE TITLE
screenshot

### ISSUE THREAD

**Issue by venkat2305** [xdelmo/random-password-generator#2]
hey, How can I take a screenshot of my webpage like yours? it looks beautiful

**Comment by xdelmo** [comment]
Thank you! Actually it is very straightforward:
- Get a screenshot of your webpage in 1280x720px
- Go to https://www.screely.com by @JurnW
- Choose Window Type: "Plain Window", Window Style: "Regular"
- Add Shadow and Dark Mode
- Add Vertical Padding: 75px, Horizontal Padding: 100px
- There you go a beautiful screenshot! 😎

### Example:
![Github Mockups](https://user-images.githubusercontent.com/84925809/199494061-672a42dc-f5f3-4f29-8ed3-9bd7f1cbabfc.png)
